
= TicTacToe
Universo Santa Tecla <USantaTecla@gmail.com>

:toc-title: Índice
:toc: left

:idprefix:
:idseparator: -
:imagesdir: images

== Modelo del Dominio

=== Vocabulario

[plantuml, ticTacToeClases, svg]
....
TicTacToe *-down-> "2" Player
TicTacToe *-down-> Board
TicTacToe *-down-> Turn
 
Turn -down-> "2" Player

Player -down-> Board
Player o-down-> "0..3" Piece
Player *-down-> Goal
Player *-down-> Color


Action <|-down- PutAction
Action <|-down- MoveAction

Piece *-down-> Color

Color <|-down- X
Color <|-down- O

Goal ..> "3" PutAction
Goal ..> "*" MoveAction
Goal ..> "3" Square

Board *-down-> "3x3" Square
Square *-down-> Coordinate
Square o-down-> "0..1" Piece

Action .down.> Piece
Action .down.> Square : target
MoveAction .down.> Square : origin

Goal <|-down- Row
Goal <|-down- Column
Goal <|-down- Diagonal
Goal <|-down- InvertedDiagonal
....

=== Estado Inicial

[plantuml, estadoInicialTicTacToe, svg]
....

together {
object ":Square" as Square11
object ":Square" as Square12
object ":Square" as Square13

object ":Square" as Square21
object ":Square" as Square22
object ":Square" as Square23

object ":Square" as Square31
object ":Square" as Square32
object ":Square" as Square33

}

object ":Coordinate" as Coordinate11 {
row = 1
column = 1
}
object ":Coordinate" as Coordinate12 {
row = 1
column = 2
}
object ":Coordinate" as Coordinate13 {
row = 1
column = 3
}

object ":Coordinate" as Coordinate21 {
row = 2
column = 1
}
object ":Coordinate" as Coordinate22 {
row = 2
column = 2
}
object ":Coordinate" as Coordinate23 {
row = 2
column = 3
}

object ":Coordinate" as Coordinate31 {
row = 3
column = 1
}
object ":Coordinate" as Coordinate32 {
row = 3
column = 2
}
object ":Coordinate" as Coordinate33 {
row = 3
column = 3
}

object ":Board" as Board

Board -->  Square11
Board -->  Square12
Board -->  Square13
Board -->  Square21
Board -->  Square22
Board -->  Square23
Board -->  Square31
Board -->  Square32
Board -->  Square33

Square11 *-down-> Coordinate11
Square12 *-down-> Coordinate12
Square13 *-down-> Coordinate13
Square21 *-down-> Coordinate21
Square22 *-down-> Coordinate22
Square23 *-down-> Coordinate23
Square31 *-down-> Coordinate31
Square32 *-down-> Coordinate32
Square33 *-down-> Coordinate33

Square11 -[hidden]right-> Square12
Square12 -[hidden]right-> Square13
Square21 -[hidden]right-> Square22
Square22 -[hidden]right-> Square23
Square31 -[hidden]right-> Square32
Square32 -[hidden]right-> Square33

Square11 -[hidden]down-> Square21
Square12 -[hidden]down-> Square22
Square13 -[hidden]down-> Square23

Square21 -[hidden]down-> Square31
Square22 -[hidden]down-> Square32
Square23 -[hidden]down-> Square33

....

=== Estado Final. Objetivo TicTacToe en 3ª fila

[plantuml, estadoFinalTicTacToe, svg]
....


together {
object ":Square" as Square11
object ":Square" as Square12
object ":Square" as Square13

object ":Square" as Square21
object ":Square" as Square22
object ":Square" as Square23

object ":Square" as Square31
object ":Square" as Square32
object ":Square" as Square33

}

object ":Coordinate" as Coordinate11 {
row = 1
column = 1
}
object ":Coordinate" as Coordinate12 {
row = 1
column = 2
}
object ":Coordinate" as Coordinate13 {
row = 1
column = 3
}

object ":Coordinate" as Coordinate21 {
row = 2
column = 1
}
object ":Coordinate" as Coordinate22 {
row = 2
column = 2
}
object ":Coordinate" as Coordinate23 {
row = 2
column = 3
}

object ":Coordinate" as Coordinate31 {
row = 3
column = 1
}
object ":Coordinate" as Coordinate32 {
row = 3
column = 2
}
object ":Coordinate" as Coordinate33 {
row = 3
column = 3
}

object ":Board" as Board

object ":Piece" as Piece1
object ":Piece" as Piece2
object ":Piece" as Piece3

object ":X" as X

Piece1 *-down-> X
Piece2 *-down-> X
Piece3 *-down-> X

object ":Piece" as Piece1b
object ":Piece" as Piece2b

object ":O" as O

Piece1b *-down-> O
Piece2b *-down-> O


Board -->  Square11
Board -->  Square12
Board -->  Square13
Board -->  Square21
Board -->  Square22
Board -->  Square23
Board -->  Square31
Board -->  Square32
Board -->  Square33

Square11 *-down-> Coordinate11
Square12 *-down-> Coordinate12
Square13 *-down-> Coordinate13
Square21 *-down-> Coordinate21
Square22 *-down-> Coordinate22
Square23 *-down-> Coordinate23
Square31 *-down-> Coordinate31
Square32 *-down-> Coordinate32
Square33 *-down-> Coordinate33

Square11 -[hidden]right-> Square12
Square12 -[hidden]right-> Square13
Square21 -[hidden]right-> Square22
Square22 -[hidden]right-> Square23
Square31 -[hidden]right-> Square32
Square32 -[hidden]right-> Square33

Square11 -[hidden]down-> Square21
Square12 -[hidden]down-> Square22
Square13 -[hidden]down-> Square23

Square21 -[hidden]down-> Square31
Square22 -[hidden]down-> Square32
Square23 -[hidden]down-> Square33

Square31 *-down-> Piece1
Square32 *-down-> Piece2
Square33 *-down-> Piece3

Square11 *-down-> Piece1b
Square21 *-down-> Piece2b

....

=== Instrucciones

<<<<<<< HEAD


== Guión de Implantaciónes
=======
[plantuml,instructions,svg]
....

@startuml
(*)  --> "put player X"
If "is tictactoe player X" then
--> [Yes] (*)
else
--> [No] "put player O"
 If "is tictactoe player O" then
 --> [Yes] (*)
 else
  If "are all tokens on board" then
--> [Yes] "move player X"
  If "is tictactoe player X" then
--> [Yes] (*)
else
--> [No] "move player O"
 If "is tictactoe player O" then
 --> [Yes] (*)
 else
  --> [No] "move player X"
 Endif
Endif
  else
  --> [No] "put player X"
  Endif
 Endif
Endif
@enduml
....
>>>>>>> bc7feb3bc1aaf2a06192df3da6054280a6d640ed

[cols="15,15,30,35" options="header"]
|===

a| Tema
a| Requisitos
a| Solución
a| Incremento

.2+a| [red]#*Modelo del Dominio*#
.2+a| [red]#TicTacToe. Requisitos. Versión 1. **Básica**#
a| [red]#TicTacToe. Solucion. Versión 1.1. **domainModel**#
a| [red]#Clases del Modelo del Dominio **pero acopladas a tecnologías de interfaz ahora y todas con la Ley del Cambio Continuo y de granos grueso con el advenimiento de nueva funcionalidad **#

a| [red]#TicTacToe. Solucion. Versión 2.1. **documentView**#
a| [red]#Clases Vistas de Texto separadas de los Modelos del Dominio **pero con Modelos de grano grueso con el advenimiento de nueva funcionalidad**#

.6+a| [blue]#*Diseño Modular y Orientado a Objetos*#
.6+a| [blue]#TicTacToe. Requisitos. Versión 2. **Gráficos**#

a| [blue]#TicTacToe. Solucion. Versión 3.2. **dv.withoutFactoryMethod**#
a| [blue]#Clase Vistas de Interfaz Gráfica de Usuario **pero con DRY en Vistas de tecnologías diferentes y con Modelos de grano grueso con el advenimiento de nueva funcionalidad**#



a| [blue]#TicTacToe. Solucion. Versión 4.2. **dv.withFactoryMethod**#
a| [blue]#Clase Vista abstracta para Open/Close de sus tecnologías **pero con Modelos de grano grueso con el advenimiento de nueva funcionalidad**#



a| [blue]#TicTacToe. Solucion. Versión 5.2. **modelViewPresenter.presentationModel**#
a| [blue]#Clases Controladoras entre Vistas y Modelos por cada Caso de Uso **pero con la clase Principal y las Vistas acopladas a cada controlador actual y futuro**#



a| [blue]#TicTacToe. Solucion. Versión 6.2. **mvp.pm.withFacade**#
a| [blue]#Clase Lógica que encapsula Controladores y Modelos **pero con Vistas con DRY en la Lógica de Control**#



a| [blue]#TicTacToe. Solucion. Versión 7.2. **mvp.pm.withoutDoubleDispatching**#
a| [blue]#Clase Estado para la Inversión de Control de Vistas a la Lógica **pero violando el Principio de Sustitución de Liskov**#



a| [blue]#TicTacToe. Solucion. Versión 8.2. **mvp.pm.withDoubleDispatching**#
a| [blue]#Clase Vistador de Controladores para Técnica de Doble Despacho#

.7+a| *Patrones de Diseño*
a| [green]#TicTacToe. Requisitos. Versión 3. **UndoRedo**#
a| [green]#TicTacToe. Solucion. Versión 9.3. **mvp.pm.withComposite**#
a| [green]#Clase Comando del menú y Controlador Compuesto de ciertos Estados para Open/Close con nuevos Casos de Uso#


.2+a| [yellow]#TicTacToe. Requisitos. Versión 4. **ClienteServidor**#
a| [yellow]#TicTacToe. Solucion. Versión 10.4. **mvp.pm.withoutProxy**#
a| [yellow]#Clase TCP/IP para tecnología de Despliegue **pero con Controladores acoplados, poco cohesivos y grano grueso con cada nueva tecnología**#



a| [yellow]#TicTacToe. Solucion. Versión 11.4. **mvp.pm.withProxy**#
a| [yellow]#Clases Proxy para Open/Close para nuevas tecnologías de Despliegue#


.2+a| [purple]#TicTacToe. Requisitos. Versión 5. **Ficheros**#
a| [purple]#TicTacToe. Solucion. Versión 12.5. **mvp.pm.withoutDAO**#
a| [purple]#Clases Vistas y Controladores para la tecnología de persistencia **pero con Modelos de grano grueso, baja cohesión y alto acoplamiento a tecnologías de persistencia de ficheros**#



a| [purple]#TicTacToe. Solucion. Versión 13.5. **mvp.pm.withDAO**#
a| [purple]#Patrón DAO#


.2+a| [lime]#TicTacToe. Requisitos. Versión 6. **BasesDatos**#
a| [lime]#TicTacToe. Solucion. Versión 14.6. **mvp.pm.withoutPrototype**#
a| [lime]#Nuevas Vistas y DAOS para la nueva tecnología  **pero con clase Principal acoplada a las tecnologías actuales y futuras de persistencia**#



a| [lime]#TicTacToe. Solucion. Versión 15.6. **mvp.pm.withPrototype**#
a| [lime]#Open/Close para arranque con configuración de persistencia#

.3+a| [red]#*Arquitectura del Software*#
.3+a| [red]#TicTacToe. Requisitos. Versión 1. **Básica**#
a| [red]#TicTacToe. Solucion. Versión 16.1. **mvp.pv**#
a| [red]#Baile de la Triada#



a| [red]#TicTacToe. Solucion. Versión 17.1. **mvp.sc**#
a| [red]#Baile de la Triada#



a| [red]#TicTacToe. Solucion. Versión 18.1. **mvc**#
a| [red]#Baile de la Triada#

|===